-- Daily auto-generated photos from さや/ゆめ
-- 1 photo per slot (morning/noon/evening) per day, generated by Gemini cron

CREATE TABLE IF NOT EXISTS daily_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  photo_date date NOT NULL,
  slot text NOT NULL CHECK (slot IN ('morning', 'noon', 'evening')),
  character_id text NOT NULL CHECK (character_id IN ('saya', 'yume', 'duo')),
  image_url text NOT NULL,
  caption text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- One photo per slot per day (idempotent cron re-runs)
  UNIQUE(photo_date, slot)
);

CREATE INDEX IF NOT EXISTS idx_daily_photos_date ON daily_photos(photo_date DESC);

ALTER TABLE daily_photos ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read daily photos (they are shared across users)
CREATE POLICY "daily_photos_authenticated_read" ON daily_photos
  FOR SELECT TO authenticated USING (true);
